class GeneralParameters:
    NUMBER_OF_FRAMES = 10

    YOLO_CAMERA_APERTURE_ANGLE = 68
    YOLO_HALF_CAMERA_APERTURE_ANGLE = YOLO_CAMERA_APERTURE_ANGLE / 2
    YOLO_CAR_SIZE = 1.6
    YOLO_DISTANCE_TO_BE_THE_SAME_CAR = 40
    YOLO_MAX_DISTANCE = 30

    LK_SEARCH_THRESHOLD_ON_THE_SURFACE = 10
    LK_DISTANCE_TO_TRACK_THRESHOLD = 255
